### PR TITLE
Let prognostic run create directories named "artifacts"

### LINKED ISSUE #1293: append.py fails when rundirectory contains "artifacts"
If a prognostic run outputs a directory named `artifacts`, the append operation fails with this error:
```
INFO:/fv3net/workflows/post_process_run/fv3post/append.py:Appending /tmp/tmp.KsNA9ogrkj/post_processed to gs://vcm-ml-scratch/online-emulator/2021-07-12/rh-model-v9-v2/fv3gfs_run
Activated service account credentials for: [ml-cluster-dev-k8s-3loq@vcm-ml.iam.gserviceaccount.com]
INFO:/fv3net/workflows/post_process_run/fv3post/append.py:Processing /tmp/tmp.KsNA9ogrkj/post_processed/logfile.000000.out
INFO:/fv3net/workflows/post_process_run/fv3post/append.py:Processing /tmp/tmp.KsNA9ogrkj/post_processed/artifacts
Traceback (most recent call last):
  File "/usr/local/bin/append_run", line 33, in <module>
    sys.exit(load_entry_point('fv3post', 'console_scripts', 'append_run')())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/fv3net/workflows/post_process_run/fv3post/append.py", line 296, in append_segment
    os.rename(tmp_rundir_file, renamed_file)
OSError: [Errno 22] Invalid argument: '/tmp/tmp.KsNA9ogrkj/post_processed/artifacts' -> '/tmp/tmp.KsNA9ogrkj/post_processed/artifacts/20160802.000000/artifacts'
```

This occurs because `fv3post.append.append_segment` operates in-place on the copied run directory, and therefore creates a file `artifacts/DATE` in the existing folder `artifacts`. It then tries to copy the parent directory into the subdirectory and fails. While this may seem like an edge case, `append` should support arbitrary file names.

### PR DESCRIPTION
**Pull request by nbren12**
Resolves #1293

### CODE REVIEW

**Comment by nbren12** [comment]
@AnnaKwa Not sure if your still looking for tasks, but this PR should be pretty straightforward to take over. I added some failing tests that can be iterated on.

**Comment by AnnaKwa** [comment]
@nbren12 Apparently I can't request you as a reviewer since you started the PR, but could you look over this? I went with creating a randomly named dir and renaming to `artifacts` in the final step. It was slightly cleaner than using another `tempfile.TemporaryDirectory()`.

**Comment by AnnaKwa** [comment]
> @nbren12 Apparently I can't request you as a reviewer since you started the PR, but could you look over this? I went with creating a randomly named dir and renaming to `artifacts` in the final step. It was slightly cleaner than using another `tempfile.TemporaryDirectory()`.

Never mind, I still need to look into this CircleCI authentication failure... I'll let you know when it's actually ready.

**Comment by AnnaKwa** [comment]
@nbren12 tests are passing now and this is ready for review- I moved the authentication out of the append_segments function since it seemed like it should be at a higher level anyways.

**Review by nbren12 — COMMENTED** [review]
Thanks for fixing this bug. I agree about pulling the authentication out of `append_segment`. This might be worth running the E2E test for.

I cannot approve this PR since I wrote the initial commit. Feel free to approve for me.

**Review by AnnaKwa — APPROVED** [review]
Noah is fine with the changes but started the PR so couldn't actually approve

**Pull request merged**
