### PR TITLE
Update `gcsfs` subtree and install it in the prognostic run image

### PR DESCRIPTION
**Pull request by spencerkclark**
This PR updates the gcsfs subtree to match the latest development version of `gcsfs`, complete with @oliverwm1's improvements to the retry logic.  It turns out that those changes broke [some import logic for exceptions in `fv3config`](https://github.com/VulcanClimateModeling/fv3config/blob/aec9ad78e5de8c675700a07c7ab6e39469035366/fv3config/filesystem.py#L12), so we'll have to discuss how to best handle that (i.e. should it be fixed upstream in `gcsfs` or in `fv3config`?).

We could of course temporarily hack a solution in our subtree here, but we'll want to address this anyway before a new release of `gcsfs` is issued.

You are encouraged to check the PR against the [Code Review Checklist](https://paper.dropbox.com/doc/Code-Review-Checklist--A4lKrs~xg7w5Gsb39N6JLNQoAg-IlsYffZgTwyKEylty7NhY).

### CODE REVIEW

**Comment by spencerkclark** [comment]
There are also some errors like this showing up, which might be related to https://github.com/dask/gcsfs/pull/381 (cc: @nbren12):
```
_____________________________ test_upload_html_gcs _____________________________
client = <google.cloud.storage.client.Client object at 0x7efbd701e190>
    def test_upload_html_gcs(client: Client):
        id_ = str(uuid.uuid4())
        html = "hello"
        mime = "text/html"
        bucket_name = "******-scratch"
        blob = f"testing/{id_}/index.html"
        url = f"gs://{bucket_name}/{blob}"
>       upload(html, url, mime)
workflows/prognostic_run_diags/tests/test_generate_report.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
workflows/prognostic_run_diags/fv3net/diagnostics/prognostic_run/views/static_report.py:42: in upload
    f.write(html)
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/core.py:121: in __exit__
    self.close()
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/core.py:149: in close
    _close(self.fobjects, self.mode)
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/core.py:209: in _close
    f.close()
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/spec.py:1535: in close
    self.flush(force=True)
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/spec.py:1401: in flush
    self._initiate_upload()
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py:1235: in _initiate_upload
    timeout=self.timeout,
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py:53: in sync
    raise result[0]
/opt/conda/envs/fv3net/lib/python3.7/site-packages/fsspec/asyn.py:20: in _runner
    result[0] = await coro
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py:1321: in initiate_upload
    headers={"X-Upload-Content-Type": content_type},
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py:332: in _call
    method, path, *args, **kwargs
<decorator-gen-2>:2: in _request
    ???
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/retry.py:110: in retry_request
    return await func(*args, **kwargs)
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py:313: in _request
    headers=self._get_headers(headers),
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/core.py:292: in _get_headers
    self.credentials.apply(out)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <gcsfs.credentials.GoogleCredentials object at 0x7efbe61ac5d0>
out = {'User-Agent': 'python-gcsfs/2021.4.0', 'X-Upload-Content-Type': 'application/octet-stream'}
    def apply(self, out):
        """Insert credential headers in-place to a dictionary"""
        self.maybe_refresh()
>       self.credentials.apply(out)
E       AttributeError: 'NoneType' object has no attribute 'apply'
/opt/conda/envs/fv3net/lib/python3.7/site-packages/gcsfs/credentials.py:168: AttributeError
```

**Comment by nbren12** [comment]
well. looks like my refactor broke gcsfs....

**Comment by oliverwm1** [comment]
We should probably delete that retry logic from fv3config (anyway I don't think those exceptions are intended to be public API for gcsfs).

**Comment by nbren12** [comment]
I agree about those exceptions. I'll look into the `NoneType` error. I wonder where the lack of coverage in the gcsfs test suite is.

**Comment by nbren12** [comment]
The versioneer versions are challenging to work with in a subtree context, I'm not sure if the issue would show up with submodules.

**Comment by spencerkclark** [comment]
Yeah, I'm +1 on removing the retry logic from `fv3config` as a way to fix this; I also agree that the use of those exceptions there was fragile.

**Comment by nbren12** [comment]
I'm looking into the NoneType issue now.

**Comment by nbren12** [comment]
#1187 is a little cleaner version of this PR. `git fetch gcsfs && git merge -s subtree gcsfs/main --squash --allow-unrelated` worked pretty well for me, I had to ensure the changes to `setup.py` and `gcsfs/__init__.py` did not get added to avoid the versioneer issues. Why were the changes to `constraints.txt` required?

**Comment by oliverwm1** [comment]
I can make an fv3config PR getting rid of the retry logic.

**Comment by spencerkclark** [comment]
> Why were the changes to constraints.txt required?

I found it was necessary to install it in the prognostic run image (which it looks like #1187 does not do yet).

> In the short run, you can use f53b58f instead of the commit that broke the authentication.

For sure -- we still need to fix the `fv3config` issue or hack the names of the modules in our subtree of gcsfs, though.

**Comment by spencerkclark** [comment]
> I can make an fv3config PR getting rid of the retry logic.

Sorry I had already started :).

**Comment by nbren12** [comment]
I issued a fix: https://github.com/dask/gcsfs/pull/390

Would be nice to have some more elaborate integration tests. I'm still nervous that it is broken.

**Comment by spencerkclark** [comment]
I forgot to fix the versioneer stuff in my latest push, but regardless, I think I'll just close this in favor of #1187 once it is updated to the latest version of gcsfs now that dask/gcsfs#390 has been merged.  Thanks for the quick bug fix @nbren12!

We just need to fix the fv3config issue now (https://github.com/VulcanClimateModeling/fv3config/pull/139), but that can be done in a separate PR.

**Pull request closed without merging**
