### PR TITLE
backport vcm.cos_zenith_angle fix for n2o paper (#1068)

### PR DESCRIPTION
**Pull request by oliverwm1**
Cherrypick a86bf0b36852b55d19fb2c23a7bf7bbd6e82b6b7 and apply it to the fv3net commit used for initial submission nudge-to-obs runs (3bd4571641e87891838123cbebacbab336560ef1)

### CODE REVIEW

**Comment by nbren12** [comment]
You might find caed182c2 relevant. The constraints file output by pip-compile needs to have the optional dependencies removed to be a valid constraints.txt for the newer pip.

**Comment by oliverwm1** [comment]
> You might find [caed182](https://github.com/VulcanClimateModeling/fv3net/commit/caed182c2afce07435861369b2054c30c49d0635) relevant. The constraints file output by pip-compile needs to have the optional dependencies removed to be a valid constraints.txt for the newer pip.

I tried cherry-picking this commit, but unfortunately there were a lot of conflicts in `constraints.txt` and I was nervous about manually resolving them and changing the version of some package.

**Comment by nbren12** [comment]
You could copy paste the sed changes. Those are the ones you need to work with the new pip.

**Comment by nbren12** [comment]
Manually editing the constraints seems ok as well since this is a backport.

**Comment by oliverwm1** [comment]
Yes, with the changes I manually implemented, everything is working as it currently stands. I think the failing test is just due to some data moving between buckets.

**Pull request closed without merging**
